#!/bin/bash
ROOT=$GOPATH/src/github.com/qjpcpu/magicbox

# abi
solc --overwrite --abi $ROOT/sol/magic_box.sol -o $ROOT/abi

# frontend
(cd $ROOT/front
browserify js/index.js > js/index.bundle.js
browserify js/canceltx.js > js/canceltx.bundle.js
echo -n 'module.exports = ' > js/abi.js
cat $ROOT/abi/MagicBox.abi >> js/abi.js
echo 'Build OK'

if [ "$1" == "dist" ];then
    mkdir -p ./dist
    rm -fr ./dist/*
    cp -a ./vendor ./js ./img ./css ./dist
    cp  ./*.html ./dist
fi
)
