#!/bin/bash
ROOT=$GOPATH/src/github.com/qjpcpu/magicbox

# abi
solc --overwrite --abi $ROOT/sol/magic_box.sol -o $ROOT/abi

# frontend
(cd $ROOT/front

# generate ABI js
echo -n 'var magicbox = ' > js/abi.js
cat $ROOT/abi/MagicBox.abi >> js/abi.js
echo -n ';' >> js/abi.js
echo '' >> js/abi.js

echo  'module.exports = { magicbox: magicbox };' >> js/abi.js
browserify ./js/index.js > ./js/index.bundle.js
browserify ./js/canceltx.js > ./js/canceltx.bundle.js
echo 'Build OK'

if [ "$1" == "dist" ];then
    mkdir -p ./dist
    rm -fr ./dist/*   
    mkdir -pv ./dist/js
    cp -a ./vendor ./img ./css ./dist
    cp ./js/*.bundle.js ./dist/js
    cp ./favicon.ico ./dist

    cp  ./*.html ./dist
fi
)
