#!/bin/bash
ROOT=$GOPATH/src/github.com/qjpcpu/magicbox

# abi
solc --overwrite --abi $ROOT/sol/magic_box.sol -o $ROOT/abi

# frontend
(cd $ROOT/front

# generate ABI js
echo -n 'var magicbox = ' > js/abi.js
cat $ROOT/abi/MagicBox.abi >> js/abi.js
echo -n ';' >> js/abi.js
echo '' >> js/abi.js

echo  'module.exports = { magicbox: magicbox };' >> js/abi.js
echo 'Build OK'

if [ "$1" == "dist" ];then
    rm -fr ./dist/*
    mkdir -p ./dist/js    
    cp -a ./vendor ./img ./css ./dist
    browserify ./js/index.js > ./dist/js/index.bundle.js
    browserify ./js/canceltx.js > ./dist/js/canceltx.bundle.js
    cp  ./*.html ./dist
fi
)
